Migrate basic load balancer Deployment/Upgrade Service Fabric cluster basic load balancer.md
Azure/Service-Fabric-Troubleshooting-Guides pull request #257
Opened 2023-05-10 21:37 UTC by jagilber

initial commit for upgrading loadbalancer from basic to standard

2023-06-07 16:35 UTC, sedwardstx requested changes

2023-06-07 16:35 UTC, sedwardstx commented on Deployment/Upgrade Service Fabric cluster basic load balancer.md
> +To upgrade basic load balancers in a Service Fabric cluster with no downtime requires the creation of a new scale set (node type), standard load balancer, and standard IP address. The new node type i
mention needing to also add NSG w/Standard LB here.

Please open PR on primary sku upgrade doc and mention NSG required for Std LB

2024-04-01 22:03 UTC, dbucce approved these changes

2024-04-01 22:05 UTC, dbucce approved these changes

2024-04-01 22:24 UTC, sedwardstx approved these changes

2024-04-01 22:24 UTC, merged